# Generated by Django 2.2.5 on 2019-10-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kids_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('image_2', models.ImageField(default='', upload_to='images/')),
                ('image_3', models.ImageField(default='', upload_to='images/')),
                ('rate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Women_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('image_2', models.ImageField(default='', upload_to='images/')),
                ('image_3', models.ImageField(default='', upload_to='images/')),
                ('rate', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='image_2',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='products',
            name='image_3',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
