# Generated by Django 2.2.5 on 2019-10-26 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_favorate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kids_products',
        ),
    ]
